//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineHistory
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string Abbreviation { get; set; }
        public string Color { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Lenght { get; set; }
        public short TravelTimeInMinute { get; set; }
        public bool IsRing { get; set; }
        public string Description { get; set; }
    
        public virtual Decade Decade { get; set; }
        public virtual LineObject LineObject { get; set; }
        public virtual Status Status { get; set; }
    }
}
