//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationPhoto
    {
        public short ID { get; set; }
        public string Photo { get; set; }
    
        public virtual HallPhoto HallPhoto { get; set; }
        public virtual PhotoAngle PhotoAngle { get; set; }
        public virtual StationObject StationObject { get; set; }
    }
}
