//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StationObject()
        {
            this.StationHistory = new HashSet<StationHistory>();
            this.StationPhoto = new HashSet<StationPhoto>();
            this.TransferObject = new HashSet<TransferObject>();
            this.TransferObject1 = new HashSet<TransferObject>();
            this.Peculiarity = new HashSet<Peculiarity>();
            this.Area = new HashSet<Area>();
        }
    
        public short ID { get; set; }
        public string Description { get; set; }
        public Nullable<byte> PlatformWidth { get; set; }
        public Nullable<short> PlatformLenght { get; set; }
        public Nullable<byte> HallHeight { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<byte> DepthTypeID { get; set; }
        public Nullable<byte> StructuralComplexID { get; set; }
        public Nullable<byte> PlatformID { get; set; }
        public byte HousingCostID { get; set; }
        public byte StateID { get; set; }
        public Nullable<byte> Traffic { get; set; }
        public Nullable<byte> TrafficTypeID { get; set; }
    
        public virtual DepthType DepthType { get; set; }
        public virtual HousingCost HousingCost { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StationHistory> StationHistory { get; set; }
        public virtual StructuralComplex StructuralComplex { get; set; }
        public virtual TrafficType TrafficType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StationPhoto> StationPhoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferObject> TransferObject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferObject> TransferObject1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Peculiarity> Peculiarity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Area> Area { get; set; }
    }
}
