//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationHistory
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public short StationObjectID { get; set; }
        public short LineObjectID { get; set; }
        public string Description { get; set; }
        public Nullable<byte> DecadeID { get; set; }
        public System.DateTime Date { get; set; }
        public byte StatusID { get; set; }
        public Nullable<byte> PossessionID { get; set; }
    
        public virtual Decade Decade { get; set; }
        public virtual LineObject LineObject { get; set; }
        public virtual StationObject StationObject { get; set; }
        public virtual Status Status { get; set; }
    }
}
