//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StructuralComplex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StructuralComplex()
        {
            this.StationObject = new HashSet<StationObject>();
        }
    
        public byte ID { get; set; }
        public byte LocationID { get; set; }
        public byte ConstructionID { get; set; }
        public byte FloorID { get; set; }
        public byte PillarID { get; set; }
    
        public virtual Construction Construction { get; set; }
        public virtual Floor Floor { get; set; }
        public virtual Location Location { get; set; }
        public virtual Pillar Pillar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StationObject> StationObject { get; set; }
    }
}
