//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransferObject()
        {
            this.TransferHistory = new HashSet<TransferHistory>();
        }
    
        public short ID { get; set; }
        public short Station_1 { get; set; }
        public short Station_2 { get; set; }
        public Nullable<byte> StateID { get; set; }
    
        public virtual State State { get; set; }
        public virtual StationObject StationObject { get; set; }
        public virtual StationObject StationObject1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferHistory> TransferHistory { get; set; }
    }
}
