//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferHistory
    {
        public int ID { get; set; }
        public byte TransferlTimeInMinute { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual TransferObject TransferObject { get; set; }
        public virtual TransferType TransferType { get; set; }
    }
}
