//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_AreaCountStations
    {
        public short ID { get; set; }
        public string Area { get; set; }
        public Nullable<int> CountStations { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string Map { get; set; }
    }
}
